[build]
  # La carpeta donde vive tu proyecto
  base = "hexis-landing"
  # El comando para construir tu aplicación
  command = "npm run build"
  # La carpeta que contiene los archivos finales listos para publicar
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200